name: rkst-php

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 4000:80
    volumes:
      - ./src:/app